-- Ajouter plus de produits exemple dans la base de données
INSERT INTO public.products (
  name, slug, description, short_description, price, prix_cents, origine, statut, stock, 
  seo_keywords, created_at, updated_at
) VALUES 
  (
    'Coffret Bien-Être Stress Relief',
    'coffret-bien-etre-stress-relief',
    'Un coffret complet pour lutter contre le stress au quotidien avec des produits naturels et artisanaux français.',
    'Coffret anti-stress avec produits naturels français',
    45.00,
    4500,
    'FR',
    'published',
    25,
    ARRAY['bien-être', 'stress', 'relaxation', 'naturel', 'français', 'coffret'],
    now(),
    now()
  ),
  (
    'Kit Énergie Matinale Bio',
    'kit-energie-matinale-bio',
    'Commencez votre journée du bon pied avec notre kit énergisant 100% bio : thé energisant, granola maison et miel local.',
    'Kit matinal énergisant 100% bio et local',
    32.50,
    3250,
    'FR',
    'published',
    40,
    ARRAY['énergie', 'matinal', 'bio', 'thé', 'granola', 'miel', 'local'],
    now(),
    now()
  ),
  (
    'Sélection Douceur & Réconfort',
    'selection-douceur-reconfort',
    'Une sélection de produits doux et réconfortants pour prendre soin de soi : tisanes, chocolat artisanal et bougie parfumée.',
    'Produits doux et réconfortants pour le bien-être',
    38.90,
    3890,
    'FR',
    'published',
    30,
    ARRAY['douceur', 'réconfort', 'tisanes', 'chocolat', 'bougie', 'bien-être'],
    now(),
    now()
  ),
  (
    'Pack Productivité & Focus',
    'pack-productivite-focus',
    'Optimisez votre concentration au travail avec notre pack spécial : thé focus, collations saines et accessoires bureau zen.',
    'Pack pour améliorer concentration et productivité',
    42.00,
    4200,
    'FR',
    'published',
    20,
    ARRAY['productivité', 'focus', 'concentration', 'bureau', 'thé', 'zen'],
    now(),
    now()
  ),
  (
    'Coffret Pause Déjeuner Healthy',
    'coffret-pause-dejeuner-healthy',
    'Transformez vos pauses déjeuner avec notre coffret healthy : soupes bio, crackers artisanaux et infusions détox.',
    'Pause déjeuner saine avec produits bio',
    35.75,
    3575,
    'UE',
    'published',
    35,
    ARRAY['healthy', 'déjeuner', 'bio', 'soupes', 'crackers', 'détox'],
    now(),
    now()
  ),
  (
    'Kit Relaxation Fin de Journée',
    'kit-relaxation-fin-journee',
    'Décompressez après une journée intense avec notre kit relaxation : huiles essentielles, tisanes relaxantes et masque détente.',
    'Kit pour se détendre en fin de journée',
    48.50,
    4850,
    'FR',
    'published',
    15,
    ARRAY['relaxation', 'fin de journée', 'huiles essentielles', 'tisanes', 'détente'],
    now(),
    now()
  ),
  (
    'Box Motivation Team Building',
    'box-motivation-team-building',
    'Renforcez la cohésion d équipe avec notre box spéciale team building : jeux collaboratifs, collations à partager et cartes motivation.',
    'Box spéciale pour renforcer la cohésion d équipe',
    55.00,
    5500,
    'FR',
    'published',
    18,
    ARRAY['team building', 'motivation', 'équipe', 'jeux', 'collaboratif', 'cohésion'],
    now(),
    now()
  ),
  (
    'Sélection Équilibre Vie Pro/Perso',
    'selection-equilibre-vie-pro-perso',
    'Trouvez votre équilibre avec notre sélection : planificateur bien-être, produits self-care et guide de méditation.',
    'Produits pour équilibrer vie professionnelle et personnelle',
    44.25,
    4425,
    'FR',
    'draft',
    12,
    ARRAY['équilibre', 'vie professionnelle', 'vie personnelle', 'planificateur', 'méditation'],
    now(),
    now()
  );