// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mahmakmfonycckirgtwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1haG1ha21mb255Y2NraXJndHdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTMwNjQsImV4cCI6MjA2MDU2OTA2NH0.axby_j9XQkOwVBZ3T4l89WzxW8X5Nr-p127j2yJjiAQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});